### ISSUE TITLE
strandness parameter? ----strandRule '1++,1--,2+-,2-+' similar to --forward_stranded

### ISSUE THREAD

**Issue by zhenyisong** [SciLifeLab/NGI-RNAseq#114]
I think that those two parameters are overlapped. If we use the first strand to construct library, the setting for HISAT2 is `--rna-strandness  fr-firststrand/RF`. If instead, we use the second strand, the setting is `fr-secondstrand/FR`. And Liguo's RSeQC package uses the `infer_expriment.py` to infer the strandness. if the output is `1++,1--,2+-,2-+`, I think this might indicate user used second strand to construct library. If `1+-,1-+,2++,2--`, it indicate that the first strand was used to construct library. (PE model). If SE model, the first strand should be `+-,-+`.

I am confused why you separate those similar output here and create two independent parameter settings. Let me know if I miss something here.

**Comment by ewels** [comment]
Hi @zhenyisong,

The `--forward_stranded` and `--reverse_stranded` pipeline flags are used to specify the expected strand of the libraries to various tools in the pipeline. We've only just added this feature and use STAR as our default mapper, so hadn't yet added those flags to the HISAT2 alignment. I'll make a note of those and add them soon.

The reason for running `infer_experiment.py` in addition to specifying either `--forward_stranded` or `--reverse_stranded` when running the pipeline is to confirm that the libraries do have the strandedness expected. For instance, we typically run libraries with a reverse stranded RNA library prep kit, but have seen samples with extreme DNA contamination which show a very different result from `infer_experiment.py`. So, this step is for quality control only.

The strandedness strings from `--forward_stranded` or `--reverse_stranded` are only _supplied_ to RSeQC for the `RPKM_saturation.py` script. They are not used by `infer_experiment.py`

I'm not sure if this answers your question or not..?

Phil

**Comment by ewels** [comment]
@zhenyisong - in replying to your comment, I found a couple of errors in the script. I've also added the strandedness flags for HISAT2. See #115.

Phil

**Comment by ewels** [comment]
Also, from your issue title: _--strandRule '1++,1--,2+-,2-+' similar to --forward_stranded_

Yes, `--strandRule` was from an earlier release before we had `--forward_stranded` and `--reverse_stranded`. It was no longer needed so I just removed it in the above PR.

Phil

**Comment by zhenyisong** [comment]
Thanks. It is a fabulous project. I tried to complete the similar task in our pipeline QC design. And Google led me to this site. However, I have to familiarize myself with the Groovy 2 first. Can this project get continous support from public funding for at least five years? BTW, can you bundle all plain txt information in one formated file, so I can parse it later and visulaize it, for example, using ggplot2 or other graph library in my own style?

**Comment by ewels** [comment]
Hi @zhenyisong,

I recommend the [Nextflow documentation](https://www.nextflow.io/docs/latest/index.html) before going into pure Groovy code - I only do that when I really have to! This pipeline is now going into production use at the Swedish [National Genomics Infrastructure](https://ngisweden.scilifelab.se/) - I can't guarantee any support, but I expect it to be maintained for the near future.

The pipeline already uses [MultiQC](http://multiqc.info/) to parse the logs into a report for visualisation. MultiQC itself also [exports parsed data](http://multiqc.info/docs/#parsed-data-directory) for downstream use. It's possible to [customise MultiQC reports](http://multiqc.info/docs/#customising-reports) extensively if you want them to have a certain style.

Phil
