### ISSUE TITLE
Running with custom reference does not produce output, but claims successful run

### ISSUE THREAD

**Issue by varemo** [SciLifeLab/NGI-RNAseq#131]
Hej!

I am trying to run the NGI-RNAseq Nextflow pipeline. I am executing the command:
`nextflow run SciLifeLab/NGI-RNAseq -r 1.0.4 -c my.config -w analysis/nextflow_workdir`

The config file _my.config_ looks like this:
```groovy
params {
  project = 'b2016346'
  aligner = 'star'
  outdir = 'analysis/nextflow_out'
  reads = 'data/RNAseq/C.Ohlsson_16_01/P6373_*_R{1,2}.fastq.gz'
  reverse_stranded = true
  genome = 'GRCm38.dna.primary_assembly'
  genomes {
    'GRCm38.dna.primary_assembly' {
      fasta = 'data/RNAseq/ref/Mus_musculus.GRCm38.dna.primary_assembly.fa'
      gtf = 'data/RNAseq/ref/Mus_musculus.GRCm38.87.gtf'
    }
  }
}
```
The pipeline runs and submits jobs and exits with claimed success. However, looking at the output, only fastqc on raw and trimmed reads, as well as building the STAR index, is carried out. *Does anyone have any idea why the remaining steps of the pipeline are not carried out?* I have failed at extracting any (for me useful) information from the log file.

Changing the run to use one of the pre-built genomes, i.e. `--genome GRCm38`, instead results in a successful run with all expected output files.

**Comment by varemo** [comment]
In fact, this was probably not the issue, but the version of nextflow. Running with v0.24.2 resulted in a successful run, at least with the `--genome GRCm38` option.

**Comment by ewels** [comment]
Thanks for this bug report and testing @varemo! We'll update the docs to warn about the required version of NextFlow..
