### ISSUE TITLE
Look into adding RSEM

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-RNAseq#132]
A few people have asked about using RSEM to generate gene counts instead of (in addition to?) StringTie. It would be interesting to look into adding this either as an addition or as an alternative to StringTie.

From e-mail thread:

> _I was wondering whether you plan to also include RSEM for transcript-level quantification in near future (Irizarry's group has shown that RSEM slightly outperforms other methods (Teng et al., Genome Biology, 2016)). StringTie was not included in the comparison though._

**Comment by Hammarn** [comment]
Looks like there is a RSEM module available on Milou.
```
rsem/1.2.29
```

**Comment by ewels** [comment]
This issue was moved to nf-core/rnaseq#70
