### ISSUE TITLE
sep="\t" should be revised to sep="\\t" in write.table()

### ISSUE THREAD

**Issue by chuan-wang** [SciLifeLab/NGI-RNAseq#14]

**Comment by ewels** [comment]
Hi @chuan-wang,

Why is this?

Phil

**Comment by chuan-wang** [comment]
R will run sep=' ' instead. It seems that R script inside a nextflow process must declare special characters using '\'

**Comment by ewels** [comment]
Ok cool. I guess it shouldn't really matter though? If it's being replaced with a literal tab character then the final effect should be the same?

**Comment by chuan-wang** [comment]
Yeah, maybe... I'm testing the generated config file to see whether it is
sensitive to this issue. /chuan

**Comment by ewels** [comment]
I think you're right that we should probably escape it though. Feels cleaner. I was just curious as I had thought that my output files looked normal.

**Comment by chuan-wang** [comment]
I think it was a space instead of a tab. It really depends on how strict
the file format is required for the next step.

**Comment by ewels** [comment]
Done in e7e3fbc69df5bd9e09160fbe27c0d5960b41c2d7
