### ISSUE TITLE
Add optional fastq-screen step

### ISSUE THREAD

**Issue by Hammarn** [SciLifeLab/NGI-RNAseq#142]
Since we run NGI QC for *all* samples that we sequences, including RNA, it would save us CPU time if we could run fastq-screen as a part of the pipeline. This would have to be optional, since most other users likely won't have a use for this.

**Comment by ewels** [comment]
For the record, I don't really like this idea as I think it will be confusing to have conflicting alignment rates in the same MultiQC report..

**Comment by Hammarn** [comment]
Fair point, and in addition to the things we discussed earlier I don't see this happening.
