### ISSUE TITLE
IDEA: DOIs for repository

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/NGI-RNAseq#188]
Hi everyone,

https://zenodo.org/ offers the possibility to create a DOI for a repository on a per-release scheme automatically. Is this something we might integrate here as well? Users could then cite the pipeline directly with a fixed version number and accompanying DOI. 

I can offer to take care of it and add a Badge to the main repository, too if there is some interest. At least I believe it doesn't harm ;-)

**Comment by MaxUlysse** [comment]
I was thinking about that for CAW before I left for vacation, I think it's a good idea.
