### ISSUE TITLE
biotypes chart showing only last 7 entries

### ISSUE THREAD

**Issue by jakubovciak** [SciLifeLab/NGI-RNAseq#198]
Hi,
is this on purpose? it selects only last seven biotypes from tmp_file , missing protein coding genes and other important groups leaving the chart quite meaningless (at least in my case).

https://github.com/SciLifeLab/NGI-RNAseq/blob/632aef19ee28fbb2f03f00cb2d54055c4a51b276/main.nf#L944

I'd suggest adding something like
``
cut -f 1,7 ${bam_featurecounts.baseName}_biotype.featureCounts.txt | sort -k 2 -n -r | head -n 10 > tmp_file
``

thanks,
JK

**Comment by ewels** [comment]
Ah no, I guess this was accidental - maybe the file that @Hammarn was looking at only had 7 categories or something?

**Comment by Hammarn** [comment]
hmm, I have no idea why I did this. I don't really see a point in restricting the categories at all to be honest. It's not _that_ many.I'll make a  PR.
