### ISSUE TITLE
Update offline docs to recommend pulling a tagged container 

### ISSUE THREAD

**Issue by arontommi** [SciLifeLab/NGI-RNAseq#220]
docker://scilifelab/ngi-rnaseq:latest does not seem to be working on bianca. Downloading and using docker://scilifelab/ngi-rnaseq:1.31  still works of course.

**Comment by MaxUlysse** [comment]
cf #222

**Comment by ewels** [comment]
Hi @arontommi,

The `:latest` docker image tag should always be considered unstable. In this case it's been broken for around a month, but just not building. We refactored it and merged a little early, meaning that it now builds and has replaced the previous `:latest`.

We recommend always running the pipelines with `-r [version]` (see [the docs](https://github.com/SciLifeLab/NGI-RNAseq/blob/master/docs/usage.md#reproducibility)) which uses a tagged version of both the code and the docker container.

I appreciate that this isn't super obvious. On the roadmap is to migrate this pipeline over to the new [nf-core](https://nf-core.github.io/) organisation. One of the guidelines that we've written there is that the `master` branch should always contain only the latest release, with development happening on other branches. This should avoid having unstable code (and containers) accidentally run for people.

Phil

**Comment by ewels** [comment]
Thanks for reporting though by the way! In this case we knew it was broken, but that's not always the case, so it's always a good idea to create issues about these things :)

**Comment by arontommi** [comment]
I just mentioned it since "singularity pull --name ngi-rnaseq.img docker://scilifelab/ngi-rnaseq" suggested for running offline automatically pulls the latest unstable one.

**Comment by ewels** [comment]
Yes - good point, we should update that.

**Comment by ewels** [comment]
Fixed in #223 and #224
