### ISSUE TITLE
STAR error when running with extra command line flags

### ISSUE THREAD

**Issue by Hammarn** [SciLifeLab/NGI-RNAseq#221]
When running with extra parameters to try to reduce the number of mismatches, STAR is occasionally triggering the following error:

```
STAR ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk
```

**Comment by ewels** [comment]
This is when we're testing out (uncommitted) usage of `--outFilterMismatchNoverLmax`

From the docs:

>`--outFilterMismatchNoverLmax 0.04`
> max number of mismatches per pair relative to read length: for 2x100b, max number of mismatches is 0.06*200=8 for the paired read

0.04 is the Encode recommendation. The STAR default is 0.3

**Comment by ewels** [comment]
I don't think we've seen this since this issue was posted, and the flag that was causing the error never made it into the pipeline. Closing now, can reopen if anyone else sees the same issue.
