### ISSUE TITLE
Dockerfile contains wrong path for conda environment

### ISSUE THREAD

**Issue by zichner** [SciLifeLab/NGI-RNAseq#222]
https://github.com/SciLifeLab/NGI-RNAseq/blob/a8e6896e0e07cabb8070157def43a568e9c791b1/Dockerfile#L9

If I am not mistaken, this line should be `ENV PATH /opt/conda/envs/ngi-rnaseq/bin:$PATH` (`ngi-rnaseq` instead of `nfcore-methylseq`)

**Comment by ewels** [comment]
Yup, already fixed in #218 but waiting to be merged (there are bigger problems with the container).

Thanks though, good spot 👍
