### ISSUE TITLE
no exon lines in the GTF file

### ISSUE THREAD

**Issue by Zeinab5** [SciLifeLab/NGI-RNAseq#229]
Hello,

I got the GTF file from CGD: http://www.candidagenome.org/download/gff/C_albicans_SC5314/Assembly22/ 
But I got this error message:
```
Fatal INPUT FILE error, no exon lines in the GTF file: albicans.gtf
Solution: check the formatting of the GTF file, it must contain some lines with exon in the 3rd column.
      Make sure the GTF file is unzipped.
      If exons are marked with a different word, use --sjdbGTFfeatureExon
```
Is it possible to make STAR accept this GTF file format? or how can I modify this GTF file to be accepted by STAR?

Thanks,
Zeinab Hefny

**Comment by ewels** [comment]
Hi @Zeinab5,

This is a little strange, http://www.candidagenome.org/download/gff/ suggests that the GTF files should use the term `exon`.

Exactly which GTF file did you use from your link? There are many in that folder.

Phil

**Comment by Zeinab5** [comment]
This is the one that I used http://www.candidagenome.org/download/gff/C_albicans_SC5314/Assembly22/C_albicans_SC5314_A22_current_features.gtf

**Comment by varemo** [comment]
The corresponding GFF file (http://www.candidagenome.org/download/gff/C_albicans_SC5314/Assembly22/C_albicans_SC5314_A22_current_features.gff) seems to contain the required fields, as oposed to the GTF which only contains "CDS". Is it possible to supply a GFF file directly to the pipeline?

**Comment by ewels** [comment]
I think it should be fine to run with a GFF instead of GTF. The format is pretty similar right? Certainly easy enough to try... Just use `--gtf [path]`

**Comment by Zeinab5** [comment]
Hi,
I solved the issue by converting  to  the GFF file from the CGD to a GTF file by using gffread and it worked.
I couldn't use the gff file directly with the pipline because gtfToGenePred can't convert gff to GenePred which I need to get the Bed12 file. it also didn't work when I didn't gave the path of the Bed12 to the pipline.

**Comment by Zeinab5** [comment]
Yes, this is the tool that I used.  
./gffread my.gff3 -T -o my.gtf

I thought that was the reason, attached the error message 
![screen shot 2018-04-20 at 15 24 42](https://user-images.githubusercontent.com/30115744/39053313-0328bb7c-44af-11e8-8a8e-552f23d4f11d.png)

**Comment by Zeinab5** [comment]
Yes, It's working fine withe this GTF file now

**Comment by ewels** [comment]
Ok great - then maybe the bind point thing was a false alarm. Strange, I'll give it another test here to be sure.

I've created a new issue for GFF support, but over at nf-core/RNAseq (we are porting our pipelines to this new nf-core organisation - see http://nf-co.re/). Issue here: https://github.com/nf-core/RNAseq/issues/15

**Comment by Zeinab5** [comment]
ok, Nice. thanks for the links
