### ISSUE TITLE
ERROR: Failed to invoke 

### ISSUE THREAD

**Issue by Zeinab5** [SciLifeLab/NGI-RNAseq#230]
Hello,

Any help to understand this error? I've already got the results and the job has completed 

![image](https://user-images.githubusercontent.com/30115744/39575385-91e579ec-4eda-11e8-9c27-b1db8b0051a1.png)

Thanks

**Comment by ewels** [comment]
Hi @Zeinab5,

By default, the pipeline tries to create a DAG (directed acyclic graph - boxes and lines showing how the pipeline is structured). To generate the image, it needs a tool called graphviz to be installed. If you follow the link in the error message and install this, you'll get an image of the pipeline and the warning will disappear. If not, then don't worry - it doesn't affect the main results of the pipeline at all.

The `Failed to invoke` thing may be a different error, I'm not totally sure. I have a feeling that we fixed something related to this a little while ago. Again, the `workflow.onComplete` code just does stuff like sending you an email when the pipeline has finished and creating a couple of summary files. It failing should have no effect on your pipeline results.

Phil

**Comment by ewels** [comment]
Closing this issue now - please feel free to reply though, we can reopen if there's something that needs following up.

Phil
