### ISSUE TITLE
Library strandedness

### ISSUE THREAD

**Issue by Zeinab5** [SciLifeLab/NGI-RNAseq#231]
Hello,
If I have a raw data and I only know that it's from a strand-specific library but I don't know is it forward or reverse,  Can I choose the unstranded parameter?

Thanks,
Zeinab

**Comment by ewels** [comment]
Hi @Zeinab5,

Yes you can. Note that the data will probably better if you use the correct strandedness - things like the gene read counts won't contain antisense reads (less noise).

If you want to run stranded, I'd recommend that you run the pipeline on a single sample and have a look at the MultiQC report. There's a plot from RSeQC which tells you the strandedness of the samples. Or just try both / guess and hope that you get it right ;) Your featureCounts assigned reads will be very low if you get it wrong.

Phil
