### ISSUE TITLE
Error: not enough memory for BAM sorting

### ISSUE THREAD

**Issue by Zeinab5** [SciLifeLab/NGI-RNAseq#234]
Hello,

After processing some samples I got this error:
![image](https://user-images.githubusercontent.com/30115744/41118191-84855c10-6a8f-11e8-913f-793071421f42.png)
![image](https://user-images.githubusercontent.com/30115744/41118220-939729ae-6a8f-11e8-808e-0ef36dfab1cd.png)

Thank you,
Zeinab

**Comment by ewels** [comment]
Hi @Zeinab5,

Yes, we've seen similar errors before with very large RNA seq inputs - how many reads do your files contain?

@jun-wan - is this the same error we saw?

Phil

**Comment by jun-wan** [comment]
@ewels  yes, usually we have the memory issue for STAR, featureCounts and dupRadar with >30M read pairs.

Jun

**Comment by Zeinab5** [comment]
If the pipeline requires more memory for these processes, could this somehow be manually changed from the hebbe_config file? Or from an additional argument in the running script command?
I am asking since I got this message:
![image](https://user-images.githubusercontent.com/30115744/41149475-f2e9d6a0-6b0b-11e8-9601-7bc5deff9045.png)

When I encountered the same problem before, only when running 2 samples I got this same error:
![image](https://user-images.githubusercontent.com/30115744/41150122-8eae0222-6b0d-11e8-8243-c23179dafd33.png)

I by-passed it by requesting 2 nodes and the pipeline was able to run. 
So, should I do the same thing for another study of 12 samples (increasing the number of nodes) If yes, how much? or should I use the suggested parameter?

**Comment by ewels** [comment]
Hi @Zeinab5,

We've just released a new version of this pipeline over at [nf-core/rnaseq](https://github.com/nf-core/rnaseq). In this release we've tried to optimise the way in which large BAM files are handled and have hopefully added some fixes for the problems you've seen here.

I'll be archiving this repository soon, so if you could grab a version of the newly renamed pipeline and give it a go that would be great! If you see any problems, please create an issue on that repo.

Cheers,

Phil
