### ISSUE TITLE
Displaying version numbers in the MultiQC report

### ISSUE THREAD

**Issue by Hammarn** [SciLifeLab/NGI-RNAseq#27]
It would be useful to have the version number of each software used when running the pipeline. 
### Steps of the pipeline that contains the version number and in which files:
- FastQC - in `.html`: `grep -e”version”`
- Trim galore: in `trimming_report` `Cutadapt version: 1.9.1`
- STAR: in `log.out` top line: `STAR version=STAR_2.5.1b`
- featureCounts in `_biotype.featureCounts.txt`: `# Program:featureCounts v1.5.0`
### These process currently _lack_ information about their version number in their log files.
- dupradar 
- MarkDuplicates 
- Preseq 
- stringtie 
- samplecorrelation

**Comment by ewels** [comment]
Thanks! Will use the version number from `fastqc_data.txt` as that's what I parse already. Shame that featureCounts doesn't have the version in the `.summary` file as that's the file I parse.

**Comment by ewels** [comment]
Duplicate issue, and implemented.
