### ISSUE TITLE
Add file merging step

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-RNAseq#29]
RNA samples are often run spread across multiple lanes. Before NextFlow is started, input files need to be merged. Each sample should have a single FastQ file or two if paired end.

eg:

```
4_160412_AC8B7GANXX_P4701_1006_1.fastq.gz
4_160412_AC8B7GANXX_P4701_1006_2.fastq.gz
5_160412_AC8B7GANXX_P4701_1006_1.fastq.gz
5_160412_AC8B7GANXX_P4701_1006_2.fastq.gz
6_160412_AC8B7GANXX_P4701_1006_1.fastq.gz
6_160412_AC8B7GANXX_P4701_1006_2.fastq.gz
1_240512_DJ3B8OSJXV_P4701_1006_1.fastq.gz
1_240512_DJ3B8OSJXV_P4701_1006_2.fastq.gz
```

becomes:

```
P4701_1006_1.fastq.gz
P4701_1006_2.fastq.gz
```

**Comment by ewels** [comment]
This will be done as part of the NGI_Pipeline - see NationalGenomicsInfrastructure/ngi_pipeline#345

**Comment by Hammarn** [comment]
We are currently using my [standalone script](https://github.com/SciLifeLab/standalone_scripts/blob/master/merge_and_rename_NGI_fastq_files.py) for this in production. 
Would need a bit of work to make it handle generic file names, and at the same time keep it from mixing samples left and right.

**Comment by ewels** [comment]
Agreed - think this is too difficult for now.
