### ISSUE TITLE
dupRadar error

### ISSUE THREAD

**Issue by drejom** [SciLifeLab/NGI-RNAseq#40]
Hi, awesome pipeline, thanks for making it available. I'm new to nextflow and R, so am not confident working this out, but I get the following error at the dupRadar step. Any ideas? Using R 3.3.0 (I note you have 3.2.3).
```
Command error:
  Loading required package: dupRadar
  Error in paste0(bam_md, "_intercept_slope.txt") : 
    object 'bam_md' not found
  Calls: cat -> paste0
  Execution halted
```

**Comment by ewels** [comment]
Hi @drejom,

Great that you're having a play with the pipeline! We don't yet have it in production and are still working out all of the bugs ourselves. This is a fairly new chunk of code and that definitely looks like a bug, I think it should be `"$bam_md"`, not just `bam_md` on [these two lines](https://github.com/SciLifeLab/NGI-RNAseq/blob/master/main.nf#L465-L466).

I'll submit a PR to fix this now.

Phil
