### ISSUE TITLE
Option for generic extra CL options for commands

### ISSUE THREAD

**Issue by Hammarn** [SciLifeLab/NGI-RNAseq#74]
Just a thought I had;
It should be possible to send extra commands to certain processes in the pipeline without having to change the code. I.e supplying them on the command line. E.g. STAR suppling it with for instance `clip3pNbases `  could sometimes be useful (i.e the Clontech SMARTer PICO prep). 
I guess we would have to set up a `params` for each process for supplying extra CL options.

**Comment by ewels** [comment]
Yup, exactly. In fact I do exactly this for the methylation pipeline (though I use them for the initial trimming step instead):
https://github.com/ewels/NGI-MethylSeq/blob/master/main.nf#L49-L85

**Comment by ewels** [comment]
@Hammarn - is this done now? We added the trimming params, was there anything else that you wanted?

**Comment by Hammarn** [comment]
Not really. The presets that we have set are really nice and we already have more flexibility than what might be expected of us. 
Though I can see there being a nice bonus to have an extra parameter for each process though, that is empty or false by default but that you could use to give additional flags/strings to the process. I.e 
`params.extra_trimgalore`, `params.extra_star` etc. I think leave this issue open for now. 
I'm not sure that anyone would actually know about it or use it if we did implement it but still, feels nice somehow ¯\_(ツ)_/¯

**Comment by ewels** [comment]
Ah ok, yes that would be nice. Kind of like the generic nextflow `clusterOptions`. I guess people would know if we documented it? ;)

**Comment by Hammarn** [comment]
>  I guess people would know if we documented it? ;)
That implies that people read the documentation - I have my doubts about that 😛

**Comment by ewels** [comment]
This issue was moved to nf-core/rnaseq#67
