### ISSUE TITLE
Plot dupRadar boxplots

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-RNAseq#81]
The current MultiQC plot for dupRadar is a little tricky to interpret.

Instead of plotting the dotted line from this plot as is done currently:
![dupradar_scatters](https://cloud.githubusercontent.com/assets/465550/23696986/446ad512-03e6-11e7-91e7-5c75af179912.png)

Plot the median values from this boxplot:
![dupradar_boxplots](https://cloud.githubusercontent.com/assets/465550/23696993/48f5e798-03e6-11e7-82fc-ddc524b1e6b7.png)

Needs these values extracting in the R script. Can then plot with the `custom_content` module if the output syntax is done properly.

**Comment by Hammarn** [comment]
Is this something that we want @ewels? And should we aim to have that in the next milestone?

**Comment by ewels** [comment]
Yes, if the data is easy to find.

**Comment by ewels** [comment]
This issue was moved to nf-core/rnaseq#68
