### ISSUE TITLE
Refactor/benchmark the RSeQC process 

### ISSUE THREAD

**Issue by Hammarn** [SciLifeLab/NGI-RNAseq#92]
We have discussed on multiple occasions earlier - the scripts run in the RseQC process have very varying memory requirements. It would save resources if we could isolate the more memory intensive one(s) into their own process. As it is now the memory requirement for all of the is governed by the need of the most intensive one.

**Comment by ewels** [comment]
Could be interesting to looking into whether running on a subsampled BAM file improves performance. I suspect that most of the plots will look identical with 1/10th data.

**Comment by ewels** [comment]
Plan: take a big BAM file and run separate `sbatch` jobs for each `rseqc` script. Then run [`jobstats -p`](https://www.uppmax.uu.se/support/user-guides/jobstats-user-guide/) on the uppmax jobs to get full profiles of each task.

This should give us info on peak memory, cpu and run time for each separate step.

**Comment by Hammarn** [comment]
Closing since this is done as of #147
